name: BlockLog
main: me.arno.blocklog.BlockLog
version: 1.3.0
author: Anerach
description: >
            A simple and effective Anti-Grief plugin.
commands:
    blocklog:
        description: Shows basic blocklog information
        aliases: bl
        usage: /<command>
    blhelp:
        description: Lists all the blocklog commands
        aliases: blh
        usage: /<command>
        permission: blocklog.help
    blreload:
        description: Reloads blocklog's config
        usage: /<command>
        permission: blocklog.reload
    blwand:
        description: Enables blocklog's wand
        usage: /<command>
        permission: blocklog.wand
    blstorage:
        description: Says the amount of internal stored blocks
        usage: /<command>
        permission: blocklog.storage
    blsave:
        description: Saves the specified amount of blocks
        usage: /<command> [blocks]
        permission: blocklog.save
    blfullsave:
        description: Saves all the blocks
        usage: /<command>
        permission: blocklog.save
    blautosave:
        description: Saves the all the blocks when the internal storage reaches a preset amount of blocks
        usage: /<command> <blocks|info>
        permission: blocklog.autosave
    blrollback:
        description: Rollback command for blocklog
        aliases: blrb
        usage: /<command> [player] <amount> <sec|min|hour|day|week>
        permission: blocklog.rollback
    blrollbackradius:
        description: Rollback command for blocklog
        aliases: [blrbradius, blrbr]
        usage: /<command> [player] <radius> <amount> <sec|min|hour|day|week>
        permission: blocklog.rollback
    blclear:
        description: Clears blocklog's history
        usage: /<command> <amount> <day|week>
        permission: blocklog.clear
    blundo:
        description: Command to undo rollbacks
        usage: /<command> [rollback]
        permission: blocklog.undo
    blconfig:
        description: Change blocklog's command values ingame
        aliases: blcfg
        usage: /<command> <get|set> <key> [value]
        permission: blocklog.config
    blconvert:
        description: Convert from one database type to another
        usage: /<command>
        permission: blocklog.convert
    blreport:
        description: Create a new grief report
        usage: /<command> <message>
        permission: blocklog.report.write
    blread:
        description: Read players their reports
        usage: /<command> [id]
        permission: blocklog.report.read
permissions:
    blocklog.admin:
        description: Gives access to all the blocklog commands
        children:
            blocklog.moderator: true
            blocklog.reload: true
            blocklog.config: true
            blocklog.clear: true
            blocklog.convert: true
            blocklog.autosave: true
    blocklog.moderator:
        description: Gives access to most of the blocklog commands
        children:
            blocklog.user: true
            blocklog.wand: true
            blocklog.notices: true
            blocklog.save: true
            blocklog.rollback: true
            blocklog.undo: true
            blocklog.storage: true
            blocklog.report.read: true
    blocklog.user:
        description: Gives access to some blocklog commands
        children:
            blocklog.help: true
            blocklog.report.write: true
    blocklog.help:
        description: Gives access to the help command
    blocklog.wand:
        description: Gives access to the wand command
    blocklog.notices:
        description: Everyone with this command will receive messages from blocklog
    blocklog.save:
        description: Gives access to the save commands
    blocklog.autosave:
        description: Gives access to the autosave command
    blocklog.rollback:
        description: Gives access to both the rollback commands
    blocklog.undo:
        description: Gives access to the undo command
    blocklog.config:
        description: Gives access to the config command
    blocklog.reload:
        description: Gives access to the reload command
    blocklog.storage:
        description: Gives access to the storage command
    blocklog.clear:
        description: Gives access to the clear command
    blocklog.convert:
        description: Gives access to the convert command
    blocklog.report.write:
        description: Gives the ability to report griefs
    blocklog.report.read:
        description: Gives the ability to read grief reports