name: BlockLog
main: me.arno.blocklog.BlockLog
version: 2.2.1
author: anerach
dev-url: http://dev.bukkit.org/server-mods/block-log
description: >
            A simple and effective log plugin with anti-grief features
softdepend: [Pail]
commands:
    blocklog:
        description: Shows basic blocklog information
        aliases: bl
        usage: /<command>
permissions:
    blocklog.admin:
        description: Gives access to all the blocklog commands
        children:
            blocklog.moderator: true
            blocklog.reload: true
            blocklog.config: true
            blocklog.purge: true
            blocklog.autosave: true
    blocklog.moderator:
        description: Gives access to most of the blocklog commands
        children:
            blocklog.user: true
            blocklog.wand: true
            blocklog.notices: true
            blocklog.save: true
            blocklog.rollback: true
            blocklog.storage: true
            blocklog.queue: true
            blocklog.report.read: true
            blocklog.search: true
    blocklog.user:
        description: Gives access to some blocklog commands
        children:
            blocklog.help: true
            blocklog.report.write: true
        default: true
    blocklog.help:
        description: Gives access to the help command
    blocklog.wand:
        description: Gives access to the wand command
    blocklog.notices:
        description: Everyone with this command will receive messages from blocklog
    blocklog.save:
        description: Gives access to the save commands
    blocklog.autosave:
        description: Gives access to the autosave command
    blocklog.rollback:
        description: Gives access to all the rollback releated commands
    blocklog.config:
        description: Gives access to the config command
    blocklog.reload:
        description: Gives access to the reload command
    blocklog.storage:
        description: Gives access to the storage command
    blocklog.queue:
        description: Gives access to the queue command
    blocklog.purge:
        description: Gives access to the purge command
    blocklog.report.write:
        description: Gives the ability to report griefs
    blocklog.report.read:
        description: Gives the ability to read grief reports
    blocklog.search:
        description: Gives access to the search command