name: BlockLog
main: me.arno.blocklog.BlockLog
version: 0.5.0
author: Anerach
description: >
            A simple and effective Anti-Grief plugin.
commands:
    blocklog:
        description: Shows basic blocklog information
        aliases: bl
        usage: /<command>
    blhelp:
        description: Lists all the blocklog commands
        aliases: blh
        usage: /<command>
        permission: blocklog.help
    blreload:
        description: Reloads blocklog's config
        usage: /<command>
        permission: blocklog.reload
    blwand:
        description: Enables blocklog's wand
        usage: /<command>
        permission: blocklog.wand
    blsave:
        description: Saves the specified amount of blocks
        usage: /<command> [blocks]
        permission: blocklog.save
    blfullsave:
        description: Saves all the blocks
        usage: /<command>
        permission: blocklog.fullsave
    blautosave:
        description: Saves the all the blocks when the internal storage reaches a preset amount of blocks
        usage: /<command> <blocks> <message>
        permission: blocklog.autosave
    blrollback:
        description: Rollback command for blocklog
        aliases: blrb
        usage: /<command> [player] <amount> <sec|min|hour|day|week>
        permission: blocklog.rollback
    blrollbackradius:
        description: Rollback command for blocklog
        aliases: [blrbradius, blrbr]
        usage: /<command> [player] <radius> <amount> <sec|min|hour|day|week>
        permission: blocklog.rollback
    blclear:
        description: Clears blocklog's history
        usage: /<command> <amount> <day|week>
        permission: blocklog.clear
    blundo:
        description: Command to undo rollbacks
        usage: /<command> [rollback]
        permission: blocklog.undo
    blconfig:
        description: Change blocklog's command values ingame
        aliases: blcfg
        usage: /<command> <get|set> <key> [value]
        permission: blocklog.config
permissions:
    blocklog.admin:
        description: Gives access to all the blocklog commands
        children:
            blocklog.help: true
            blocklog.notices: true
            blocklog.config: true
            blocklog.clear: true
            blocklog.reload: true
            blocklog.wand: true
            blocklog.rollback: true
            blocklog.undo: true
            blocklog.save: true
            blocklog.fullsave: true
            blocklog.autosave: true
    blocklog.moderator:
        description: Gives access to most of the blocklog commands
        children:
            blocklog.help: true
            blocklog.notices: true
            blocklog.wand: true
            blocklog.rollback: true
            blocklog.undo: true
            blocklog.save: true
            blocklog.fullsave: true
    blocklog.help:
        description: Gives access to the help command
    blocklog.notices:
        description: Everyone with this command will receive messages from blocklog
    blocklog.config:
        description: Gives access to the config command
    blocklog.clear:
        description: Gives access to the clear command
    blocklog.reload:
        description: Gives access to the reload command
    blocklog.wand:
        description: Gives access to the wand command
    blocklog.rollback:
        description: Gives access to both the rollback commands
    blocklog.save:
        description: Gives access to the save command
    blocklog.fullsave:
        description: Gives access to the fullsave command
    blocklog.autosave:
        description: Gives access to the autosave command