CREATE TABLE IF NOT EXISTS `blocklog_undos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rollback` INT UNSIGNED NOT NULL,
  `player` VARCHAR(255) NOT NULL,
  `date` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  KEY `rollback` (`rollback`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;