CREATE TABLE IF NOT EXISTS `blocklog_blocks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `player` VARCHAR(255) NOT NULL,
  `entity` VARCHAR(255) NOT NULL,
  `block` SMALLINT UNSIGNED NOT NULL,
  `data` SMALLINT UNSIGNED NOT NULL,
  `old_block` SMALLINT UNSIGNED NOT NULL,
  `old_data` SMALLINT UNSIGNED NOT NULL,
  `type` TINYINT UNSIGNED NOT NULL,
  `rollback` INT UNSIGNED NOT NULL,
  `world` VARCHAR(75) NOT NULL,
  `x` SMALLINT NOT NULL,
  `y` SMALLINT NOT NULL,
  `z` SMALLINT NOT NULL,
  `date` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  KEY `player` (`player`,`entity`),
  KEY `location` (`x`,`y`,`z`,`world`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;