CREATE TABLE IF NOT EXISTS `blocklog_chests` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `player` VARCHAR(255) NOT NULL,
  `item` SMALLINT UNSIGNED NOT NULL,
  `amount` SMALLINT UNSIGNED NOT NULL,
  `data` SMALLINT UNSIGNED NOT NULL,
  `type` TINYINT UNSIGNED NOT NULL,
  `world` VARCHAR(75) NOT NULL,
  `x` SMALLINT NOT NULL,
  `y` SMALLINT NOT NULL,
  `z` SMALLINT NOT NULL,
  `date` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  KEY `player` (`player`),
  KEY `item` (`item`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;