CREATE TABLE IF NOT EXISTS `blocklog_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `player` VARCHAR(255) NOT NULL,
  `data` VARCHAR(255) NOT NULL,
  `type` INT UNSIGNED NOT NULL,
  `world` VARCHAR(75) NOT NULL,
  `x` SMALLINT NOT NULL,
  `y` SMALLINT NOT NULL,
  `z` SMALLINT NOT NULL,
  `date` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  KEY `player` (`player`),
  KEY `location` (`world`,`x`,`y`,`z`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;