CREATE TABLE IF NOT EXISTS 'blocklog_kills' (
	'id' INTEGER PRIMARY KEY NOT NULL,
	'victem' VARCHAR(75) NOT NULL,
	'killer' VARCHAR(75) NOT NULL,
	'world' VARCHAR(75) NOT NULL,
	'x' INTEGER NOT NULL,
	'y' INTEGER NOT NULL,
	'z' INTEGER NOT NULL,
	'date' INTEGER NOT NULL
);