CREATE TABLE IF NOT EXISTS 'blocklog_blocks' (
	'id' INTEGER PRIMARY KEY NOT NULL,
	'player' VARCHAR(75) NOT NULL,
	'world' VARCHAR(75) NOT NULL,
	'block_id' INTEGER NOT NULL,
	'type' INTEGER NOT NULL,
	'rollback_id' INTEGER NOT NULL DEFAULT '0',
	'x' DOUBLE NOT NULL,
	'y' DOUBLE NOT NULL,
	'z' DOUBLE NOT NULL,
	'date' INTEGER NOT NULL
);